CREATE SEQUENCE primary_key;
DROP TABLE IF EXISTS feature_access;
CREATE TABLE feature_access (id BIGINT NOT NULL AUTO_INCREMENT, email VARCHAR(100) NOT NULL, feature_name VARCHAR(100) NOT NULL, enable BOOLEAN NOT NULL, PRIMARY KEY (id));
